package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CustomerBestbuyAggregatedMonthly generated by hbm2java
 */
@Entity
@Table(name = "customer_bestbuy_aggregated_monthly", catalog = "lovefashion1", uniqueConstraints = @UniqueConstraint(columnNames = "period") )
public class CustomerBestbuyAggregatedMonthly implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private CustomerEntity customerEntity;
	private Date period;
	private String customerName;
	private String address;
	private int qtyOrder;
	private double paidOrder;

	public CustomerBestbuyAggregatedMonthly() {
	}

	public CustomerBestbuyAggregatedMonthly(CustomerEntity customerEntity, int qtyOrder, double paidOrder) {
		this.customerEntity = customerEntity;
		this.qtyOrder = qtyOrder;
		this.paidOrder = paidOrder;
	}

	public CustomerBestbuyAggregatedMonthly(CustomerEntity customerEntity, Date period, String customerName,
			String address, int qtyOrder, double paidOrder) {
		this.customerEntity = customerEntity;
		this.period = period;
		this.customerName = customerName;
		this.address = address;
		this.qtyOrder = qtyOrder;
		this.paidOrder = paidOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public CustomerEntity getCustomerEntity() {
		return this.customerEntity;
	}

	public void setCustomerEntity(CustomerEntity customerEntity) {
		this.customerEntity = customerEntity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "period", unique = true, length = 10)
	public Date getPeriod() {
		return this.period;
	}

	public void setPeriod(Date period) {
		this.period = period;
	}

	@Column(name = "customer_name")
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "qty_order", nullable = false)
	public int getQtyOrder() {
		return this.qtyOrder;
	}

	public void setQtyOrder(int qtyOrder) {
		this.qtyOrder = qtyOrder;
	}

	@Column(name = "paid_order", nullable = false, precision = 22, scale = 0)
	public double getPaidOrder() {
		return this.paidOrder;
	}

	public void setPaidOrder(double paidOrder) {
		this.paidOrder = paidOrder;
	}

}
