package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeneralEntity generated by hbm2java
 */
@Entity
@Table(name = "general_entity", catalog = "lovefashion1")
public class GeneralEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer entityId;
	private Integer taxClassId;
	private String material;
	private String climate;
	private String pattern;
	private String collar;
	private String sleeve;
	private String active;
	private Double weight;
	private String metaDescription;
	private String metaKeyword;
	private String metaTitle;
	private String description;
	private String urlKey;
	private String urlPath;
	private Date createdAt;
	private Date updatedAt;
	private Short isNew;
	private Short status;
	private Date newsFromDate;
	private Date newsToDate;
	private String image;
	private Short sale;
	private Double specialPrice;
	private Date specialFromDate;
	private Date specialToDate;
	private Set<ProductGalleryEntity> productGalleryEntities = new HashSet<ProductGalleryEntity>(0);
	private Set<ProductEntity> productEntities = new HashSet<ProductEntity>(0);

	public GeneralEntity() {
	}

	public GeneralEntity(Integer taxClassId, String material, String climate, String pattern, String collar,
			String sleeve, String active, Double weight, String metaDescription, String metaKeyword, String metaTitle,
			String description, String urlKey, String urlPath, Date createdAt, Date updatedAt, Short isNew,
			Short status, Date newsFromDate, Date newsToDate, String image, Short sale, Double specialPrice,
			Date specialFromDate, Date specialToDate, Set<ProductGalleryEntity> productGalleryEntities,
			Set<ProductEntity> productEntities) {
		this.taxClassId = taxClassId;
		this.material = material;
		this.climate = climate;
		this.pattern = pattern;
		this.collar = collar;
		this.sleeve = sleeve;
		this.active = active;
		this.weight = weight;
		this.metaDescription = metaDescription;
		this.metaKeyword = metaKeyword;
		this.metaTitle = metaTitle;
		this.description = description;
		this.urlKey = urlKey;
		this.urlPath = urlPath;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isNew = isNew;
		this.status = status;
		this.newsFromDate = newsFromDate;
		this.newsToDate = newsToDate;
		this.image = image;
		this.sale = sale;
		this.specialPrice = specialPrice;
		this.specialFromDate = specialFromDate;
		this.specialToDate = specialToDate;
		this.productGalleryEntities = productGalleryEntities;
		this.productEntities = productEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@Column(name = "tax_class_id")
	public Integer getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(Integer taxClassId) {
		this.taxClassId = taxClassId;
	}

	@Column(name = "material")
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "climate")
	public String getClimate() {
		return this.climate;
	}

	public void setClimate(String climate) {
		this.climate = climate;
	}

	@Column(name = "pattern")
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@Column(name = "collar")
	public String getCollar() {
		return this.collar;
	}

	public void setCollar(String collar) {
		this.collar = collar;
	}

	@Column(name = "sleeve")
	public String getSleeve() {
		return this.sleeve;
	}

	public void setSleeve(String sleeve) {
		this.sleeve = sleeve;
	}

	@Column(name = "active")
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "weight", precision = 22, scale = 0)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Column(name = "meta_description")
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	@Column(name = "meta_keyword", length = 65535)
	public String getMetaKeyword() {
		return this.metaKeyword;
	}

	public void setMetaKeyword(String metaKeyword) {
		this.metaKeyword = metaKeyword;
	}

	@Column(name = "meta_title")
	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url_key")
	public String getUrlKey() {
		return this.urlKey;
	}

	public void setUrlKey(String urlKey) {
		this.urlKey = urlKey;
	}

	@Column(name = "url_path")
	public String getUrlPath() {
		return this.urlPath;
	}

	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "is_new")
	public Short getIsNew() {
		return this.isNew;
	}

	public void setIsNew(Short isNew) {
		this.isNew = isNew;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "news_from_date", length = 19)
	public Date getNewsFromDate() {
		return this.newsFromDate;
	}

	public void setNewsFromDate(Date newsFromDate) {
		this.newsFromDate = newsFromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "news_to_date", length = 19)
	public Date getNewsToDate() {
		return this.newsToDate;
	}

	public void setNewsToDate(Date newsToDate) {
		this.newsToDate = newsToDate;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "sale")
	public Short getSale() {
		return this.sale;
	}

	public void setSale(Short sale) {
		this.sale = sale;
	}

	@Column(name = "special_price", precision = 22, scale = 0)
	public Double getSpecialPrice() {
		return this.specialPrice;
	}

	public void setSpecialPrice(Double specialPrice) {
		this.specialPrice = specialPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "special_from_date", length = 19)
	public Date getSpecialFromDate() {
		return this.specialFromDate;
	}

	public void setSpecialFromDate(Date specialFromDate) {
		this.specialFromDate = specialFromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "special_to_date", length = 19)
	public Date getSpecialToDate() {
		return this.specialToDate;
	}

	public void setSpecialToDate(Date specialToDate) {
		this.specialToDate = specialToDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "generalEntity")
	public Set<ProductGalleryEntity> getProductGalleryEntities() {
		return this.productGalleryEntities;
	}

	public void setProductGalleryEntities(Set<ProductGalleryEntity> productGalleryEntities) {
		this.productGalleryEntities = productGalleryEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "generalEntity")
	public Set<ProductEntity> getProductEntities() {
		return this.productEntities;
	}

	public void setProductEntities(Set<ProductEntity> productEntities) {
		this.productEntities = productEntities;
	}

}
