package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InventoryStock generated by hbm2java
 */
@Entity
@Table(name = "inventory_stock", catalog = "lovefashion1")
public class InventoryStock implements java.io.Serializable {

	private Short stockId;
	private String stockName;
	private Set<InventoryStockStatus> inventoryStockStatuses = new HashSet<InventoryStockStatus>(0);
	private Set<InventoryStockItem> inventoryStockItems = new HashSet<InventoryStockItem>(0);

	public InventoryStock() {
	}

	public InventoryStock(String stockName, Set<InventoryStockStatus> inventoryStockStatuses,
			Set<InventoryStockItem> inventoryStockItems) {
		this.stockName = stockName;
		this.inventoryStockStatuses = inventoryStockStatuses;
		this.inventoryStockItems = inventoryStockItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stock_id", unique = true, nullable = false)
	public Short getStockId() {
		return this.stockId;
	}

	public void setStockId(Short stockId) {
		this.stockId = stockId;
	}

	@Column(name = "stock_name")
	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventoryStock")
	public Set<InventoryStockStatus> getInventoryStockStatuses() {
		return this.inventoryStockStatuses;
	}

	public void setInventoryStockStatuses(Set<InventoryStockStatus> inventoryStockStatuses) {
		this.inventoryStockStatuses = inventoryStockStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventoryStock")
	public Set<InventoryStockItem> getInventoryStockItems() {
		return this.inventoryStockItems;
	}

	public void setInventoryStockItems(Set<InventoryStockItem> inventoryStockItems) {
		this.inventoryStockItems = inventoryStockItems;
	}

}
