package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InventoryStockStatus generated by hbm2java
 */
@Entity
@Table(name = "inventory_stock_status", catalog = "lovefashion1")
public class InventoryStockStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InventoryStockStatusId id;
	private InventoryStock inventoryStock;
	private ProductEntity productEntity;
	private int qty;
	private short stockStatus;

	public InventoryStockStatus() {
	}

	public InventoryStockStatus(InventoryStockStatusId id, InventoryStock inventoryStock, ProductEntity productEntity,
			int qty, short stockStatus) {
		this.id = id;
		this.inventoryStock = inventoryStock;
		this.productEntity = productEntity;
		this.qty = qty;
		this.stockStatus = stockStatus;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false) ),
			@AttributeOverride(name = "stockId", column = @Column(name = "stock_id", nullable = false) ) })
	public InventoryStockStatusId getId() {
		return this.id;
	}

	public void setId(InventoryStockStatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stock_id", nullable = false, insertable = false, updatable = false)
	public InventoryStock getInventoryStock() {
		return this.inventoryStock;
	}

	public void setInventoryStock(InventoryStock inventoryStock) {
		this.inventoryStock = inventoryStock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public ProductEntity getProductEntity() {
		return this.productEntity;
	}

	public void setProductEntity(ProductEntity productEntity) {
		this.productEntity = productEntity;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Column(name = "stock_status", nullable = false)
	public short getStockStatus() {
		return this.stockStatus;
	}

	public void setStockStatus(short stockStatus) {
		this.stockStatus = stockStatus;
	}

}
