package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesShipmentItem generated by hbm2java
 */
@Entity
@Table(name = "sales_shipment_item", catalog = "lovefashion1")
public class SalesShipmentItem implements java.io.Serializable {

	private Integer entityId;
	private SalesShipment salesShipment;
	private Double rowTotal;
	private Double price;
	private Double weight;
	private Integer qty;
	private Integer productId;
	private String name;
	private String sku;

	public SalesShipmentItem() {
	}

	public SalesShipmentItem(SalesShipment salesShipment) {
		this.salesShipment = salesShipment;
	}

	public SalesShipmentItem(SalesShipment salesShipment, Double rowTotal, Double price, Double weight, Integer qty,
			Integer productId, String name, String sku) {
		this.salesShipment = salesShipment;
		this.rowTotal = rowTotal;
		this.price = price;
		this.weight = weight;
		this.qty = qty;
		this.productId = productId;
		this.name = name;
		this.sku = sku;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "entity_id", unique = true, nullable = false)
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public SalesShipment getSalesShipment() {
		return this.salesShipment;
	}

	public void setSalesShipment(SalesShipment salesShipment) {
		this.salesShipment = salesShipment;
	}

	@Column(name = "row_total", precision = 22, scale = 0)
	public Double getRowTotal() {
		return this.rowTotal;
	}

	public void setRowTotal(Double rowTotal) {
		this.rowTotal = rowTotal;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "weight", precision = 22, scale = 0)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

}
