package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesInvoice generated by hbm2java
 */
@Entity
@Table(name = "sales_invoice", catalog = "lovefashion1")
public class SalesInvoice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String entityId;
	private SalesOrder salesOrder;
	private Store store;
	private Double taxAmount;
	private Double discountAmount;
	private Double grandTotal;
	private Double shippingAmount;
	private Double subtotalInclTax;
	private Integer totalQty;
	private Double subtotal;
	private Integer billingAddressId;
	private Integer shippingAddressId;
	private Date createdAt;
	private Date updatedAt;
	private Set<SalesInvoiceItem> salesInvoiceItems = new HashSet<SalesInvoiceItem>(0);

	public SalesInvoice() {
	}

	public SalesInvoice(String entityId, SalesOrder salesOrder) {
		this.entityId = entityId;
		this.salesOrder = salesOrder;
	}

	public SalesInvoice(String entityId, SalesOrder salesOrder, Store store, Double taxAmount, Double discountAmount,
			Double grandTotal, Double shippingAmount, Double subtotalInclTax, Integer totalQty, Double subtotal,
			Integer billingAddressId, Integer shippingAddressId, Date createdAt, Date updatedAt,
			Set<SalesInvoiceItem> salesInvoiceItems) {
		this.entityId = entityId;
		this.salesOrder = salesOrder;
		this.store = store;
		this.taxAmount = taxAmount;
		this.discountAmount = discountAmount;
		this.grandTotal = grandTotal;
		this.shippingAmount = shippingAmount;
		this.subtotalInclTax = subtotalInclTax;
		this.totalQty = totalQty;
		this.subtotal = subtotal;
		this.billingAddressId = billingAddressId;
		this.shippingAddressId = shippingAddressId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.salesInvoiceItems = salesInvoiceItems;
	}

	@Id

	@Column(name = "entity_id", unique = true, nullable = false, length = 60)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "tax_amount", precision = 22, scale = 0)
	public Double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "discount_amount", precision = 22, scale = 0)
	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "grand_total", precision = 22, scale = 0)
	public Double getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(Double grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "shipping_amount", precision = 22, scale = 0)
	public Double getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(Double shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	@Column(name = "subtotal_incl_tax", precision = 22, scale = 0)
	public Double getSubtotalInclTax() {
		return this.subtotalInclTax;
	}

	public void setSubtotalInclTax(Double subtotalInclTax) {
		this.subtotalInclTax = subtotalInclTax;
	}

	@Column(name = "total_qty")
	public Integer getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(Integer totalQty) {
		this.totalQty = totalQty;
	}

	@Column(name = "subtotal", precision = 22, scale = 0)
	public Double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "billing_address_id")
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@Column(name = "shipping_address_id")
	public Integer getShippingAddressId() {
		return this.shippingAddressId;
	}

	public void setShippingAddressId(Integer shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesInvoice")
	public Set<SalesInvoiceItem> getSalesInvoiceItems() {
		return this.salesInvoiceItems;
	}

	public void setSalesInvoiceItems(Set<SalesInvoiceItem> salesInvoiceItems) {
		this.salesInvoiceItems = salesInvoiceItems;
	}

}
