package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SalesPaymentTransaction generated by hbm2java
 */
@Entity
@Table(name = "sales_payment_transaction", catalog = "lovefashion1", uniqueConstraints = @UniqueConstraint(columnNames = {
		"order_id", "txn_id", "payment_id" }) )
public class SalesPaymentTransaction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer transactionId;
	private SalesOrder salesOrder;
	private SalesOrderPayment salesOrderPayment;
	private String txnId;
	private String txnType;
	private String st;
	private String additionalInformation;
	private Date createdAt;

	public SalesPaymentTransaction() {
	}

	public SalesPaymentTransaction(SalesOrder salesOrder, String st) {
		this.salesOrder = salesOrder;
		this.st = st;
	}

	public SalesPaymentTransaction(SalesOrder salesOrder, SalesOrderPayment salesOrderPayment, String txnId,
			String txnType, String st, String additionalInformation, Date createdAt) {
		this.salesOrder = salesOrder;
		this.salesOrderPayment = salesOrderPayment;
		this.txnId = txnId;
		this.txnType = txnType;
		this.st = st;
		this.additionalInformation = additionalInformation;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "transaction_id", unique = true, nullable = false)
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id")
	public SalesOrderPayment getSalesOrderPayment() {
		return this.salesOrderPayment;
	}

	public void setSalesOrderPayment(SalesOrderPayment salesOrderPayment) {
		this.salesOrderPayment = salesOrderPayment;
	}

	@Column(name = "txn_id", length = 100)
	public String getTxnId() {
		return this.txnId;
	}

	public void setTxnId(String txnId) {
		this.txnId = txnId;
	}

	@Column(name = "txn_type", length = 15)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "st", nullable = false)
	public String getSt() {
		return this.st;
	}

	public void setSt(String st) {
		this.st = st;
	}

	@Column(name = "additional_information", length = 65535)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
