package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesCreditmemo generated by hbm2java
 */
@Entity
@Table(name = "sales_creditmemo", catalog = "lovefashion1")
public class SalesCreditmemo implements java.io.Serializable {

	private String entityId;
	private SalesOrder salesOrder;
	private Store store;
	private Double grandTotal;
	private Double shippingAmount;
	private Double subtotalInclTax;
	private Double discountAmount;
	private Double subtotal;
	private Double taxAmount;
	private Integer shippingAddressId;
	private Integer billingAddressId;
	private Date createdAt;
	private Date updatedAt;
	private Set<SalesCreditmemoItem> salesCreditmemoItems = new HashSet<SalesCreditmemoItem>(0);

	public SalesCreditmemo() {
	}

	public SalesCreditmemo(String entityId, SalesOrder salesOrder) {
		this.entityId = entityId;
		this.salesOrder = salesOrder;
	}

	public SalesCreditmemo(String entityId, SalesOrder salesOrder, Store store, Double grandTotal,
			Double shippingAmount, Double subtotalInclTax, Double discountAmount, Double subtotal, Double taxAmount,
			Integer shippingAddressId, Integer billingAddressId, Date createdAt, Date updatedAt,
			Set<SalesCreditmemoItem> salesCreditmemoItems) {
		this.entityId = entityId;
		this.salesOrder = salesOrder;
		this.store = store;
		this.grandTotal = grandTotal;
		this.shippingAmount = shippingAmount;
		this.subtotalInclTax = subtotalInclTax;
		this.discountAmount = discountAmount;
		this.subtotal = subtotal;
		this.taxAmount = taxAmount;
		this.shippingAddressId = shippingAddressId;
		this.billingAddressId = billingAddressId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.salesCreditmemoItems = salesCreditmemoItems;
	}

	@Id

	@Column(name = "entity_id", unique = true, nullable = false, length = 60)
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "grand_total", precision = 22, scale = 0)
	public Double getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(Double grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "shipping_amount", precision = 22, scale = 0)
	public Double getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(Double shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	@Column(name = "subtotal_incl_tax", precision = 22, scale = 0)
	public Double getSubtotalInclTax() {
		return this.subtotalInclTax;
	}

	public void setSubtotalInclTax(Double subtotalInclTax) {
		this.subtotalInclTax = subtotalInclTax;
	}

	@Column(name = "discount_amount", precision = 22, scale = 0)
	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "subtotal", precision = 22, scale = 0)
	public Double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "tax_amount", precision = 22, scale = 0)
	public Double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(Double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "shipping_address_id")
	public Integer getShippingAddressId() {
		return this.shippingAddressId;
	}

	public void setShippingAddressId(Integer shippingAddressId) {
		this.shippingAddressId = shippingAddressId;
	}

	@Column(name = "billing_address_id")
	public Integer getBillingAddressId() {
		return this.billingAddressId;
	}

	public void setBillingAddressId(Integer billingAddressId) {
		this.billingAddressId = billingAddressId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesCreditmemo")
	public Set<SalesCreditmemoItem> getSalesCreditmemoItems() {
		return this.salesCreditmemoItems;
	}

	public void setSalesCreditmemoItems(Set<SalesCreditmemoItem> salesCreditmemoItems) {
		this.salesCreditmemoItems = salesCreditmemoItems;
	}

}
