package com.example.entity;
// Generated Jan 4, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaxClass generated by hbm2java
 */
@Entity
@Table(name = "tax_class", catalog = "lovefashion1")
public class TaxClass implements java.io.Serializable {

	private Short classId;
	private String className;
	private Set<TaxCalculation> taxCalculations = new HashSet<TaxCalculation>(0);

	public TaxClass() {
	}

	public TaxClass(String className) {
		this.className = className;
	}

	public TaxClass(String className, Set<TaxCalculation> taxCalculations) {
		this.className = className;
		this.taxCalculations = taxCalculations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "class_id", unique = true, nullable = false)
	public Short getClassId() {
		return this.classId;
	}

	public void setClassId(Short classId) {
		this.classId = classId;
	}

	@Column(name = "class_name", nullable = false)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxClass")
	public Set<TaxCalculation> getTaxCalculations() {
		return this.taxCalculations;
	}

	public void setTaxCalculations(Set<TaxCalculation> taxCalculations) {
		this.taxCalculations = taxCalculations;
	}

}
